services:
  looper:
    image: looper-vps:latest
    container_name: looper
    restart: unless-stopped
    expose:
    - "8080"
    volumes:
    - looper2_db:/app
    environment:
    - LOOPER_RELEASE=1
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080/api/healthcheck"]
      interval: 3s
      timeout: 2s
      retries: 3
      start_period: 15s

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
    - "80:80"
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
    - looper

volumes:
  looper2_db:
